### PR TITLE
options.pair_additions -> additions

### PR DESCRIPTION
**Pull request by jrowlingson**
Great plugin - nice and simple. I noticed this inconsistency with the doc (untested but assume it would fix).

### CODE REVIEW

**Comment by nat-418** [comment]
Thanks for catching this. I am gonna leave the old name in there in case anyone had  a config relying on it and I will remove it later.

**Comment by nat-418** [comment]
thanks for catching that

**Comment by jrowlingson** [comment]
@nat-418 - it looks like the commit history got mangled with this one. Should we back this one out?

**Comment by jrowlingson** [comment]
You might try resetting the commit and forcing a new commit on `main` e.g.:

 `git reset --soft HEAD~1 && git commit -m'options.pair_additions -> additions' && git push origin --force`

**Pull request closed without merging**
